name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up client environment
        env:
          CLIENT_SECRET_KEY: ${{ secrets.CLIENT_SECRET_KEY }}
        run: echo "SECRET_KEY=${CLIENT_SECRET_KEY}" > client/.env
      - name: Install client dependencies
        working-directory: client
        run: npm install
      - name: Set up server environment
        env:
          SERVER_SECRET_KEY: ${{ secrets.SERVER_SECRET_KEY }}
        run: echo "SECRET_KEY=${SERVER_SECRET_KEY}" > server/.env
      - name: Install server dependencies
        working-directory: server
        run: npm install
        
        
  
