name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: slack

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Navigate to the server directory
        run: cd slack/server

      - name: Install server dependencies and Restart server
        run: |
          npm ci
          git pull
          pm2 restart server

      - name: Navigate to the client directory
        run: cd ../client

      - name: Install client dependencies and Restart React app
        run: |
          npm ci
          git pull
          pm2 restart my-react-app
