name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: slack

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Restart server and Pull latest changes
        run: |
          cd slack/server
          git pull
          pm2 restart server

      - name: Restart React app and Pull latest changes
        run: |
          cd slack/client
          git pull
          pm2 restart my-react-app
