name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Restart server and Pull latest changes
      run: |
        cd /home/ubuntu/slack/server
        git pull
        pm2 restart server
    - name: Restart React app
      run: |
        cd /home/ubuntu/slack/client
        git pull
        pm2 restart my-react-app
