name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Print the current working directory
      - name: Print current directory
        run: |
          pwd

      - name: Set up client and server environments
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          PORT: ${{ secrets.PORT }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
        run: |
          cd slack/client
          echo "REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}" > .env
          npm install

          cd ../../server
          echo "PORT=${PORT}" > .env
          echo "MONGODB_URI=${MONGODB_URI}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "CORS_ORIGIN=${CORS_ORIGIN}" >> .env
          echo "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}" >> .env
          echo "ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}" >> .env
          npm install
