name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up client environment
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
        run: |
          echo "REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}" > client/.env
          npm install
        working-directory: client
      - name: Set up server environment
        env:
          PORT: ${{ secrets.PORT }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
        run: |
          echo "PORT=${PORT}" > server/.env
          echo "MONGODB_URI=${MONGODB_URI}" >> server/.env
          echo "DB_NAME=${DB_NAME}" >> server/.env
          echo "CORS_ORIGIN=${CORS_ORIGIN}" >> server/.env
          echo "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}" >> server/.env
          echo "ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}" >> server/.env
          npm install
        working-directory: server
