name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: slack

      - name: Navigate to the server directory and Use Node.js
        run: |
          cd slack/server
          npm config set cache /home/ubuntu/.npm
          npm ci
          cd ../client
          npm config set cache /home/ubuntu/.npm
          npm ci
      - name: Restart server and Pull latest changes
        run: |
          cd slack/server
          git pull
          pm2 restart server

      - name: Restart React app and Pull latest changes
        run: |
          cd ../client
          git pull
          pm2 restart my-react-app
